In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime
import requests
import json
import os
from sqlalchemy import create_engine
import pymysql
%matplotlib inline
%config InlineBackend.figure_format='retina'

In [153]:
def createDayDataframe(filename):
    path = "tongsdata/"
    filedate = filename.split(".")[0].split("-")

    with open(path + filename, 'r', encoding='utf-8') as fin:
        data_json = json.loads(fin.read())

    #  Create X DataFrame
    todayData = {time: data_json[time]['currently'] for time in data_json}
    todayData_DF = pd.DataFrame(todayData).T

    #  Create y DataFrame
    energyBalanceFilename = "energyBalance/Energy_Balance_{}_{}_{}.csv".format(filedate[0], filedate[1], filedate[2]) #change due to json filename
    energyBalance = pd.read_csv(path + energyBalanceFilename, delimiter=";")

    energyBalance_DF = pd.DataFrame(index=energyBalance.iloc[:-1,0].apply(lambda x: x[2:-1]))
    energyBalance_DF['PV Power Generation'] = energyBalance['PV power generation / Mean values [W]  '].values[:-1]
    energyBalance_DF = energyBalance_DF[energyBalance_DF != ' ']
    energyBalance_DF = energyBalance_DF.dropna()

    #  Join X y DataFrame
    data = todayData_DF.join(energyBalance_DF)
    return data

def cleanDataframe(masterDF):
    masterData_cleaned = masterDF.reset_index()
    masterData_cleaned = masterData_cleaned.rename(columns={'index': 'time_of_day'})
    masterData_cleaned = masterData_cleaned[masterData_cleaned['PV Power Generation'].notna()]
    #masterData_cleaned['month'] = masterData_cleaned['time'].apply(datetime.datetime.fromtimestamp).apply(lambda x: x.month)
    masterData_cleaned['cloudCover'] = masterData_cleaned['cloudCover'].fillna(value=masterData_cleaned['cloudCover'].mean())
    masterData_cleaned['PV Power Generation'] = masterData_cleaned['PV Power Generation'].apply(lambda x: x.replace(",", "")).astype('float')
    return masterData_cleaned

def featureEngineering(masterDF):
    #masterDF = masterDF.drop(columns=['icon', 'summary', 'time', 'windBearing', 'windGust', 'ozone', 'precipIntensity', 'precipProbability','pressure', 'precipType', 'uvIndex'])
    masterDF = masterDF.drop(columns=['icon', 'summary', 'time', 'windBearing', 'windGust', 'ozone', 'precipIntensity', 'precipProbability','pressure', 'precipType'])
    
    #masterDF = pd.get_dummies(masterDF, columns=['time_of_day', 'precipType', 'uvIndex', 'month'])
    masterDF = pd.get_dummies(masterDF, columns=['time_of_day'])
    return masterDF

Darksky key : 2b423d0c90e52bb805ccf6af1f305d7c ,bf11a6cc1e3fb105f612b086f6cefe19

In [3]:
def callApi(date):
    key = "bf11a6cc1e3fb105f612b086f6cefe19"
    latitude = "13.8282"
    longitude = "100.614"
    
    url = "https://api.darksky.net/forecast/{}/{},{}".format(key, latitude, longitude) +"?exclude=currently,minutely,daily"
    
    response = requests.get(url=url)
    return response

In [4]:
def one_month(month, year):
    date = datetime.datetime(year=year, month=month, day=1) #change day here
    nextMonth = date.month + 1
    while(date.month != nextMonth):
        yield date
        date = date + datetime.timedelta(days=1)   
        
def one_day(date):
    tomorrow = date + datetime.timedelta(days=1)
    while(date.day != tomorrow.day):
        yield date
        date = date + datetime.timedelta(minutes=15)

In [5]:
def write_json(filename, data):
    with open("Testdate/" + filename + ".json", "w", encoding='utf-8') as fout:
        fout.write(json.dumps(data))

In [6]:
def loadjson(predict_date):
    date = pd.to_datetime(predict_date)
    filename = date.strftime("%Y-%m-%d") #change to Y-m-d because file will arrange better
    result = callApi(date)
    d = json.loads(result.text)
    df = pd.DataFrame.from_dict(d['hourly']['data'])
    df['time'] = pd.to_datetime(df['time'],unit='s')
    df.set_index('time',inplace=True)
    df1 = df[filename]
    newdf = pd.DataFrame(np.repeat(df1.values,4,axis=0))
    newdf.columns = df1.columns
    
    maketime = []
    date = predict_date.replace("_","-")
    date = pd.to_datetime(date)
    tomorrow = date + datetime.timedelta(days=1)
    while(date.day != tomorrow.day):
        a = date.strftime("%H:%M")
        maketime.append(a)
        date = date + datetime.timedelta(minutes=15)
    newdf["time"] = maketime
    newdf.set_index('time',inplace=True)
    savetojson = newdf.to_json(r'C:\Users\User\Documents\Senior-Project\Testdate/' + filename + '.json')

In [7]:
def clean1(date):
    date = date.split("-")
    path = "tongsdata/"
    filename = "energyBalance/Energy_Balance_{}_{}_{}.csv".format(date[0], date[1], date[2])
    rawdata=pd.read_csv(path + filename, delimiter=";" )
    deleteindex=rawdata.loc[rawdata.loc[pd.IndexSlice[:,'Battery discharging / Mean values [W] ']]==' '].index
    rawdata.drop(deleteindex,inplace=True)
    rawdata.rename(columns={' ':'Time'},inplace=True)
    rawdata['Time']=rawdata['Time'].str.replace('[^\d]','')
    rawdata['Time']=date[0]+date[1]+date[2]+rawdata['Time']
    rawdata['Time']=pd.to_datetime(rawdata.Time)
    rawdata.set_index('Time', inplace=True)
    for i in rawdata.columns:
        if i != 'Direct consumption / Mean values [W] ' and i != 'Battery discharging / Mean values [W] ' and i!='External energy supply / Mean values [W] ' and i != 'PV power generation / Mean values [W]  ':
            rawdata.drop([i],axis=1,inplace=True)
    for i in rawdata.columns:
        rawdata[i].fillna('0',inplace=True)
        rawdata[i]=rawdata[i].apply(lambda x: x.replace(' ', '0'))
        rawdata[i]=rawdata[i].str.replace('\D','').astype(int)
    rawdata['Consumption']=rawdata['Direct consumption / Mean values [W] ']+rawdata['Battery discharging / Mean values [W] ']+rawdata['External energy supply / Mean values [W] ']
    rawdata.rename(columns={'PV power generation / Mean values [W]  ':'Generation'},inplace=True)
    rawdata.drop(['Direct consumption / Mean values [W] ', 'Battery discharging / Mean values [W] ','External energy supply / Mean values [W] '],axis=1,inplace=True)
    return rawdata

In [145]:
def predictgen(predict_date):
    path = "Testdate/" #from load into file above
    filename = predict_date.replace("_",'-') + '.json'
    
    with open(path + filename, 'r', encoding='utf-8') as fin:
        data_json = json.loads(fin.read())
    
    todayData_DF = pd.DataFrame.from_dict(data_json)
    todayData_DF.index.names=['time_of_day']
    todayData_DF = todayData_DF.loc['06:30':'18:00']
    todayData_DF = todayData_DF.reset_index()
    todayData_DF['cloudCover'] = todayData_DF['cloudCover'].fillna(value=todayData_DF['cloudCover'].mean())
    dropcolumns=['icon', 'summary', 'time', 'windBearing', 'windGust', 'ozone', 'precipIntensity', 'precipProbability','pressure','precipType','uvIndex']
    for i in dropcolumns:
        if i in todayData_DF.columns:
            todayData_DF = todayData_DF.drop(columns=[i])
    todayData_DF = pd.get_dummies(todayData_DF, columns=['time_of_day'])

    masterData_for_predict = masterData.drop(columns=['PV Power Generation'])
    for i in range(len(masterData_for_predict.columns)) : #drop power balance
        if masterData_for_predict.columns[i] not in todayData_DF.columns:
            todayData_DF.insert(i, masterData.columns[i+1], 0)
    missingvalue = todayData_DF[todayData_DF.isna().any(axis=1)].index
    
    col = ['apparentTemperature','cloudCover','dewPoint','humidity','temperature','visibility','windSpeed']
    for col in todayData_DF:
        todayData_DF[col] = pd.to_numeric(todayData_DF[col], errors='coerce')
    #if todayData_DF.isna().loc[0,'uvIndex']:
    #    todayData_DF.loc[0,'uvIndex'] = 0
    todayData_DF=todayData_DF.interpolate(limit_direction='both')
    
    first_predict = todayData_DF.astype('float').values
    
    results_first_predict = exported_pipeline.predict(first_predict)
    results_first_predict = np.array(results_first_predict).tolist()
    for i in range(25):
        results_first_predict.insert(0,0.0)
    for j in range (24):
        results_first_predict.append(0.0)
    return results_first_predict

แก้โดยใส่uvIndexเอง

In [155]:
def predictgen(predict_date):
    path = "tongsdata/"
    filename = predict_date.replace("_",'-') + '.json'
    
    with open(path + filename, 'r', encoding='utf-8') as fin:
        data_json = json.loads(fin.read())
    
    todayData = {time: data_json[time]['currently'] for time in data_json}
    todayData_DF = pd.DataFrame(todayData).T
    
    todayData_DF.index.names=['time_of_day']
    todayData_DF = todayData_DF.loc['06:30':'18:00']
    todayData_DF = todayData_DF.reset_index()
    #todayData_DF['month'] = todayData_DF['time'].apply(datetime.datetime.fromtimestamp).apply(lambda x: x.month)
    
    todayData_DF['cloudCover'] = todayData_DF['cloudCover'].fillna(value=todayData_DF['cloudCover'].mean())
    #todayData_DF['cloudCover'] = 0.19
    dropcolumns=['icon', 'summary', 'time', 'windBearing', 'windGust', 'ozone', 'precipIntensity', 'precipProbability','pressure','precipType']
    for i in dropcolumns:
        if i in todayData_DF.columns:
            todayData_DF = todayData_DF.drop(columns=[i])
    #todayData_DF = pd.get_dummies(todayData_DF, columns=['time_of_day', 'precipType', 'uvIndex', 'month'])
    todayData_DF = pd.get_dummies(todayData_DF, columns=['time_of_day'])

    masterData_for_predict = masterData.drop(columns=['PV Power Generation'])
    for i in range(len(masterData_for_predict.columns)) : #drop power balance
        if masterData_for_predict.columns[i] not in todayData_DF.columns:
            todayData_DF.insert(i, masterData.columns[i+1], 0)
    missingvalue = todayData_DF[todayData_DF.isna().any(axis=1)].index
    
    col = ['apparentTemperature','cloudCover','dewPoint','humidity','temperature','visibility','windSpeed']
    for col in todayData_DF:
        todayData_DF[col] = pd.to_numeric(todayData_DF[col], errors='coerce')
    if todayData_DF.isna().loc[0,'uvIndex']:
        todayData_DF.loc[0,'uvIndex'] = 0
    todayData_DF=todayData_DF.interpolate(limit_direction='both')
    
    first_predict = todayData_DF.astype('float').values
    
    results_first_predict = exported_pipeline.predict(first_predict)
    results_first_predict = np.array(results_first_predict).tolist()
    for i in range(25):
        results_first_predict.insert(0,0.0)
    for j in range (24):
        results_first_predict.append(0.0)
    return results_first_predict

In [129]:
def predictgen(predict_date):
    path = "Testdate/" #from load into file above
    filename = predict_date.replace("_",'-') + '.json'
    
    with open(path + filename, 'r', encoding='utf-8') as fin:
        data_json = json.loads(fin.read())
    
    todayData_DF = pd.DataFrame.from_dict(data_json)
    todayData_DF.index.names=['time_of_day']
    todayData_DF = todayData_DF.loc['06:30':'18:00']
    todayData_DF = todayData_DF.reset_index()
    todayData_DF['cloudCover'] = todayData_DF['cloudCover'].fillna(value=todayData_DF['cloudCover'].mean())
    dropcolumns=['icon', 'summary', 'time', 'windBearing', 'windGust', 'ozone', 'precipIntensity', 'precipProbability','pressure','precipType']
    for i in dropcolumns:
        if i in todayData_DF.columns:
            todayData_DF = todayData_DF.drop(columns=[i])
    todayData_DF = pd.get_dummies(todayData_DF, columns=['time_of_day'])
    
    masterData_for_predict = masterData.drop(columns=['PV Power Generation'])
    for i in range(len(masterData_for_predict.columns)) : #drop power balancea
        if masterData_for_predict.columns[i] not in todayData_DF.columns:
            todayData_DF.insert(i, masterData.columns[i+1], 0)
    missingvalue = todayData_DF[todayData_DF.isna().any(axis=1)].index

    col = ['apparentTemperature','cloudCover','dewPoint','humidity','temperature','visibility','windSpeed']
    for col in todayData_DF:
        todayData_DF[col] = pd.to_numeric(todayData_DF[col], errors='coerce')
    
    if todayData_DF.isna().loc[0,'uvIndex']:
        todayData_DF.loc[0,'uvIndex'] = 0
    if todayData_DF.loc[0,'uvIndex'] > 0:
        todayData_DF['uvIndex'] = np.nan
        todayData_DF.loc[0,'uvIndex'] = 0
        todayData_DF.loc[46,'uvIndex'] = 0
        todayData_DF.loc[23,'uvIndex'] = 10
    
    todayData_DF=todayData_DF.interpolate(limit_direction='both')
    first_predict = todayData_DF.astype('float').values
    
    results_first_predict = exported_pipeline.predict(first_predict)
    results_first_predict = np.array(results_first_predict).tolist()
    for i in range(25):
        results_first_predict.insert(0,0.0)
    for j in range (24):
        results_first_predict.append(0.0)
    return results_first_predict

### รันแค่ครั้งเดียวเพื่อ fit model

In [154]:
import os
import pandas as pd
import json
import datetime

files = os.listdir("tongsdata/")

#files.remove(".DS_Store")
files.remove("energyBalance")

masterData = pd.DataFrame()

for file in files:
    r = createDayDataframe(file).loc['06:30':'18:00']
    #print(file, r.shape)
    masterData = pd.concat([masterData, r], axis=0)

masterData = cleanDataframe(masterData)
masterData = featureEngineering(masterData)

features = list(masterData.drop(columns=['PV Power Generation']).columns)

masterData = masterData.dropna()

X = masterData.drop(columns=['PV Power Generation']).astype('float').values
y = masterData['PV Power Generation'].astype('float').values


from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

training_features, testing_features, training_target, testing_target = train_test_split(X, y)

# Average CV score on the training set was:-91867.4890210794
exported_pipeline = RandomForestRegressor(bootstrap=False, max_features=0.3, min_samples_leaf=1, min_samples_split=7, n_estimators=100)

exported_pipeline.fit(training_features, training_target)
results = exported_pipeline.predict(testing_features)

#from sklearn.metrics import mean_squared_error, r2_score ,mean_absolute_error
#print(mean_squared_error(testing_target, results), 
#mean_absolute_error(testing_target, results), 
#r2_score(testing_target, results))

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  app.launch_new_instance()

In [156]:
predict_date="2019-04-29"

In [76]:
loadjson(predict_date)

In [157]:
generation=predictgen(predict_date)

In [159]:
generation

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 71.96800000000002,
 134.66583333333338,
 296.7756666666666,
 537.4023333333333,
 662.8915000000002,
 702.9911666666667,
 728.4471666666666,
 1050.253333333333,
 946.1121666666669,
 693.319666666667,
 707.3696666666667,
 971.7358333333334,
 1274.6071666666667,
 1148.5955000000001,
 2305.726666666667,
 2071.1476666666667,
 1614.0868333333344,
 1576.1793333333342,
 1618.3253333333344,
 1650.7545000000007,
 1693.3195000000007,
 1513.0550000000003,
 1589.9498333333333,
 1600.006833333334,
 2131.434666666667,
 1620.3670000000004,
 1362.566,
 1384.1875,
 1544.8105000000003,
 1966.1743333333334,
 2655.651,
 2496.8419999999996,
 2466.763666666667,
 2481.2038333333335,
 2298.4158333333335,
 2167.912333333333,
 1923.6443333333327,
 1770.4380000000006,
 1489.575666666667,
 1297.6463333333334,
 1168.4656666666667,
 838.4598333333336,
 745.3231666666668,
 523.7384999999999,
 138.29083333333335,
 269.3933333333334,
 175.98666666666665,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0]

In [160]:
df2=clean1(predict_date)

df2["Forecasted Generation"] = generation

df2

                     Generation  Consumption  Forecasted Generation
Time
2019-04-29 00:15:00           0         3628               0.000000
2019-04-29 00:30:00           0         2851               0.000000
2019-04-29 00:45:00           0         2911               0.000000
2019-04-29 01:00:00           0         2594               0.000000
2019-04-29 01:15:00           0         2732               0.000000
2019-04-29 01:30:00           0         2578               0.000000
2019-04-29 01:45:00           0         2805               0.000000
2019-04-29 02:00:00           0         2762               0.000000
2019-04-29 02:15:00           0         2347               0.000000
2019-04-29 02:30:00           0         2209               0.000000
2019-04-29 02:45:00           0         2567               0.000000
2019-04-29 03:00:00           0         2343               0.000000
2019-04-29 03:15:00           0         2619               0.000000
2019-04-29 03:30:00           0         2339               0.000000
2019-04-29 03:45:00           0         2380               0.000000
2019-04-29 04:00:00           0         2483               0.000000
2019-04-29 04:15:00           0         2145               0.000000
2019-04-29 04:30:00           0         2133               0.000000
2019-04-29 04:45:00           0         2476               0.000000
2019-04-29 05:00:00           0         3392               0.000000
2019-04-29 05:15:00           0         2358               0.000000
2019-04-29 05:30:00           0         1947               0.000000
2019-04-29 05:45:00           0         1396               0.000000
2019-04-29 06:00:00           0         1432               0.000000
2019-04-29 06:15:00           0         1264               0.000000
2019-04-29 06:30:00          51         1646              71.968000
2019-04-29 06:45:00         149          993             134.665833
2019-04-29 07:00:00         340          786             296.775667
2019-04-29 07:15:00         521          672             537.402333
2019-04-29 07:30:00         748          794             662.891500
2019-04-29 07:45:00         682          786             702.991167
2019-04-29 08:00:00         692          724             728.447167
2019-04-29 08:15:00        1078          975            1050.253333
2019-04-29 08:30:00         942          941             946.112167
2019-04-29 08:45:00         646         1540             693.319667
2019-04-29 09:00:00         606         1743             707.369667
2019-04-29 09:15:00        1072         1426             971.735833
2019-04-29 09:30:00        1299         1022            1274.607167
2019-04-29 09:45:00         997         1244            1148.595500
2019-04-29 10:00:00        2429         1232            2305.726667
2019-04-29 10:15:00        2337         1149            2071.147667
2019-04-29 10:30:00        1609         1011            1614.086833
2019-04-29 10:45:00        1481         1482            1576.179333
2019-04-29 11:00:00        2145         1401            1618.325333
2019-04-29 11:15:00        1673          762            1650.754500
2019-04-29 11:30:00        1851         1224            1693.319500
2019-04-29 11:45:00        1445         1001            1513.055000
2019-04-29 12:00:00        1813         1362            1589.949833
2019-04-29 12:15:00        1480         1417            1600.006833
2019-04-29 12:30:00        2309         2363            2131.434667
2019-04-29 12:45:00        2059         2336            1620.367000
2019-04-29 13:00:00        1210         2798            1362.566000
2019-04-29 13:15:00        1360         4002            1384.187500
2019-04-29 13:30:00        2434         3547            1544.810500
2019-04-29 13:45:00        2539         3758            1966.174333
2019-04-29 14:00:00        2865         2239            2655.651000
2019-04-29 14:15:00        2701         2001            2496.842000
2019-04-29 14:30:00        2605         1931            2466.763667
2019-04-29 14:45:00        2464         2031            2481.203833
2019-04-29 15:00:00        2299         2025            2298.415833
2019-04-29 15:15:00        2218         2515            2167.912333
2019-04-29 15:30:00        1686         1276            1923.644333
2019-04-29 15:45:00        1798          920            1770.438000
2019-04-29 16:00:00        1548         1103            1489.575667
2019-04-29 16:15:00        1198          993            1297.646333
2019-04-29 16:30:00        1231          918            1168.465667
2019-04-29 16:45:00         980          918             838.459833
2019-04-29 17:00:00         779          937             745.323167
2019-04-29 17:15:00         606         2081             523.738500
2019-04-29 17:30:00         460         3015             138.290833
2019-04-29 17:45:00         264         3732             269.393333
2019-04-29 18:00:00         173         3118             175.986667
2019-04-29 18:15:00         100         2699               0.000000
2019-04-29 18:30:00          35         3321               0.000000
2019-04-29 18:45:00           5         4341               0.000000
2019-04-29 19:00:00           0         4381               0.000000
2019-04-29 19:15:00           0         4650               0.000000
2019-04-29 19:30:00           0         4183               0.000000
2019-04-29 19:45:00           0         3979               0.000000
2019-04-29 20:00:00           0         3946               0.000000
2019-04-29 20:15:00           0         3873               0.000000
2019-04-29 20:30:00           0         4280               0.000000
2019-04-29 20:45:00           0         4793               0.000000
2019-04-29 21:00:00           0         4624               0.000000
2019-04-29 21:15:00           0         4282               0.000000
2019-04-29 21:30:00           0         4144               0.000000
2019-04-29 21:45:00           0         3992               0.000000
2019-04-29 22:00:00           0         3796               0.000000
2019-04-29 22:15:00           0         3697               0.000000
2019-04-29 22:30:00           0         3561               0.000000
2019-04-29 22:45:00           0         3355               0.000000
2019-04-29 23:00:00           0         3318               0.000000
2019-04-29 23:15:00           0         3445               0.000000
2019-04-29 23:30:00           0         3367               0.000000
2019-04-29 23:45:00           0         3058               0.000000
2019-04-29 00:00:00           0            0               0.000000

In [161]:
def maape(actual: np.ndarray, predicted: np.ndarray):
    """
    Mean Arctangent Absolute Percentage Error
    Note: result is NOT multiplied by 100
    """
    EPSILON = 1e-10
    return np.mean(np.arctan(np.abs((actual - predicted) / (actual + EPSILON))))*100

In [163]:
df2["AAPE"] = 0

for index, row in df2.iterrows():
    error = maape(row["Generation"], row["Forecasted Generation"])
    df2.loc[index,'AAPE'] = error

In [164]:
df2

                     Generation  Consumption  Forecasted Generation       AAPE
Time
2019-04-29 00:15:00           0         3628               0.000000   0.000000
2019-04-29 00:30:00           0         2851               0.000000   0.000000
2019-04-29 00:45:00           0         2911               0.000000   0.000000
2019-04-29 01:00:00           0         2594               0.000000   0.000000
2019-04-29 01:15:00           0         2732               0.000000   0.000000
2019-04-29 01:30:00           0         2578               0.000000   0.000000
2019-04-29 01:45:00           0         2805               0.000000   0.000000
2019-04-29 02:00:00           0         2762               0.000000   0.000000
2019-04-29 02:15:00           0         2347               0.000000   0.000000
2019-04-29 02:30:00           0         2209               0.000000   0.000000
2019-04-29 02:45:00           0         2567               0.000000   0.000000
2019-04-29 03:00:00           0         2343               0.000000   0.000000
2019-04-29 03:15:00           0         2619               0.000000   0.000000
2019-04-29 03:30:00           0         2339               0.000000   0.000000
2019-04-29 03:45:00           0         2380               0.000000   0.000000
2019-04-29 04:00:00           0         2483               0.000000   0.000000
2019-04-29 04:15:00           0         2145               0.000000   0.000000
2019-04-29 04:30:00           0         2133               0.000000   0.000000
2019-04-29 04:45:00           0         2476               0.000000   0.000000
2019-04-29 05:00:00           0         3392               0.000000   0.000000
2019-04-29 05:15:00           0         2358               0.000000   0.000000
2019-04-29 05:30:00           0         1947               0.000000   0.000000
2019-04-29 05:45:00           0         1396               0.000000   0.000000
2019-04-29 06:00:00           0         1432               0.000000   0.000000
2019-04-29 06:15:00           0         1264               0.000000   0.000000
2019-04-29 06:30:00          51         1646              71.968000  39.007044
2019-04-29 06:45:00         149          993             134.665833   9.590732
2019-04-29 07:00:00         340          786             296.775667  12.645206
2019-04-29 07:15:00         521          672             537.402333   3.147201
2019-04-29 07:30:00         748          794             662.891500  11.329418
2019-04-29 07:45:00         682          786             702.991167   3.076912
2019-04-29 08:00:00         692          724             728.447167   5.262069
2019-04-29 08:15:00        1078          975            1050.253333   2.573334
2019-04-29 08:30:00         942          941             946.112167   0.436533
2019-04-29 08:45:00         646         1540             693.319667   7.311967
2019-04-29 09:00:00         606         1743             707.369667  16.574214
2019-04-29 09:15:00        1072         1426             971.735833   9.325870
2019-04-29 09:30:00        1299         1022            1274.607167   1.877596
2019-04-29 09:45:00         997         1244            1148.595500  15.089585
2019-04-29 10:00:00        2429         1232            2305.726667   5.070715
2019-04-29 10:15:00        2337         1149            2071.147667  11.327102
2019-04-29 10:30:00        1609         1011            1614.086833   0.316148
2019-04-29 10:45:00        1481         1482            1576.179333   6.417868
2019-04-29 11:00:00        2145         1401            1618.325333  24.077284
2019-04-29 11:15:00        1673          762            1650.754500   1.329599
2019-04-29 11:30:00        1851         1224            1693.319500   8.498149
2019-04-29 11:45:00        1445         1001            1513.055000   4.706211
2019-04-29 12:00:00        1813         1362            1589.949833  12.241308
2019-04-29 12:15:00        1480         1417            1600.006833   8.090869
2019-04-29 12:30:00        2309         2363            2131.434667   7.675034
2019-04-29 12:45:00        2059         2336            1620.367000  20.989440
2019-04-29 13:00:00        1210         2798            1362.566000  12.542572
2019-04-29 13:15:00        1360         4002            1384.187500   1.778305
2019-04-29 13:30:00        2434         3547            1544.810500  35.025743
2019-04-29 13:45:00        2539         3758            1966.174333  22.189568
2019-04-29 14:00:00        2865         2239            2655.651000   7.294157
2019-04-29 14:15:00        2701         2001            2496.842000   7.544262
2019-04-29 14:30:00        2605         1931            2466.763667   5.301604
2019-04-29 14:45:00        2464         2031            2481.203833   0.698196
2019-04-29 15:00:00        2299         2025            2298.415833   0.025410
2019-04-29 15:15:00        2218         2515            2167.912333   2.257852
2019-04-29 15:30:00        1686         1276            1923.644333  14.002909
2019-04-29 15:45:00        1798          920            1770.438000   1.532805
2019-04-29 16:00:00        1548         1103            1489.575667   3.772391
2019-04-29 16:15:00        1198          993            1297.646333   8.298621
2019-04-29 16:30:00        1231          918            1168.465667   5.075599
2019-04-29 16:45:00         980          918             838.459833  14.343688
2019-04-29 17:00:00         779          937             745.323167   4.320395
2019-04-29 17:15:00         606         2081             523.738500  13.492037
2019-04-29 17:30:00         460         3015             138.290833  61.030151
2019-04-29 17:45:00         264         3732             269.393333   2.042645
2019-04-29 18:00:00         173         3118             175.986667   1.726225
2019-04-29 18:15:00         100         2699               0.000000  78.539816
2019-04-29 18:30:00          35         3321               0.000000  78.539816
2019-04-29 18:45:00           5         4341               0.000000  78.539816
2019-04-29 19:00:00           0         4381               0.000000   0.000000
2019-04-29 19:15:00           0         4650               0.000000   0.000000
2019-04-29 19:30:00           0         4183               0.000000   0.000000
2019-04-29 19:45:00           0         3979               0.000000   0.000000
2019-04-29 20:00:00           0         3946               0.000000   0.000000
2019-04-29 20:15:00           0         3873               0.000000   0.000000
2019-04-29 20:30:00           0         4280               0.000000   0.000000
2019-04-29 20:45:00           0         4793               0.000000   0.000000
2019-04-29 21:00:00           0         4624               0.000000   0.000000
2019-04-29 21:15:00           0         4282               0.000000   0.000000
2019-04-29 21:30:00           0         4144               0.000000   0.000000
2019-04-29 21:45:00           0         3992               0.000000   0.000000
2019-04-29 22:00:00           0         3796               0.000000   0.000000
2019-04-29 22:15:00           0         3697               0.000000   0.000000
2019-04-29 22:30:00           0         3561               0.000000   0.000000
2019-04-29 22:45:00           0         3355               0.000000   0.000000
2019-04-29 23:00:00           0         3318               0.000000   0.000000
2019-04-29 23:15:00           0         3445               0.000000   0.000000
2019-04-29 23:30:00           0         3367               0.000000   0.000000
2019-04-29 23:45:00           0         3058               0.000000   0.000000
2019-04-29 00:00:00           0            0               0.000000   0.000000

In [165]:
df2.loc[predict_date +' 06:30:00':predict_date +' 18:00:00','AAPE'].mean()

10.048564756244287

In [144]:
from sklearn.feature_selection import SelectFromModel
featuresImportance = pd.DataFrame()
featuresImportance['Feature Name'] = features
featuresImportance['Importance'] = exported_pipeline.feature_importances_

featuresImportance.sort_values('Importance', ascending=False).head()

          Feature Name  Importance
4          temperature    0.127848
3             humidity    0.115238
0  apparentTemperature    0.066648
5           visibility    0.057304
2             dewPoint    0.054490

In [149]:
path = "Testdate/" #from load into file above
filename = predict_date.replace("_",'-') + '.json'

with open(path + filename, 'r', encoding='utf-8') as fin:
    data_json = json.loads(fin.read())

todayData_DF = pd.DataFrame.from_dict(data_json)
todayData_DF.index.names=['time_of_day']
todayData_DF = todayData_DF.loc['06:30':'18:00']
todayData_DF = todayData_DF.reset_index()
todayData_DF['cloudCover'] = todayData_DF['cloudCover'].fillna(value=todayData_DF['cloudCover'].mean())
dropcolumns=['icon', 'summary', 'time', 'windBearing', 'windGust', 'ozone', 'precipIntensity', 'precipProbability','pressure','precipType']
for i in dropcolumns:
    if i in todayData_DF.columns:
        todayData_DF = todayData_DF.drop(columns=[i])
todayData_DF = pd.get_dummies(todayData_DF, columns=['time_of_day'])

masterData_for_predict = masterData.drop(columns=['PV Power Generation'])
for i in range(len(masterData_for_predict.columns)) : #drop power balance
    if masterData_for_predict.columns[i] not in todayData_DF.columns:
        todayData_DF.insert(i, masterData.columns[i+1], 0)
missingvalue = todayData_DF[todayData_DF.isna().any(axis=1)].index

col = ['apparentTemperature','cloudCover','dewPoint','humidity','temperature','visibility','windSpeed']
for col in todayData_DF:
    todayData_DF[col] = pd.to_numeric(todayData_DF[col], errors='coerce')

In [127]:
if todayData_DF.isna().loc[0,'uvIndex']:
    todayData_DF.loc[0,'uvIndex'] = 0
if todayData_DF.loc[0,'uvIndex'] > 0:
    todayData_DF['uvIndex'] = np.nan
    todayData_DF.loc[0,'uvIndex'] = 0
    todayData_DF.loc[46,'uvIndex'] = 0
    todayData_DF.loc[23,'uvIndex'] = 10

todayData_DF=todayData_DF.interpolate(limit_direction='both')

In [150]:
todayData_DF

,apparentTemperature,cloudCover,dewPoint,humidity,temperature,uvIndex,visibility,windSpeed,time_of_day_06:30,time_of_day_06:45,...,time_of_day_15:45,time_of_day_16:00,time_of_day_16:15,time_of_day_16:30,time_of_day_16:45,time_of_day_17:00,time_of_day_17:15,time_of_day_17:30,time_of_day_17:45,time_of_day_18:00
0,103.38,0.48,71.80,0.47,94.96,9,10.0,11.58,1,0,...,0,0,0,0,0,0,0,0,0,0
1,103.38,0.48,71.80,0.47,94.96,9,10.0,11.58,0,1,...,0,0,0,0,0,0,0,0,0,0
2,104.37,0.54,71.00,0.44,96.40,7,10.0,12.13,0,0,...,0,0,0,0,0,0,0,0,0,0
3,104.37,0.54,71.00,0.44,96.40,7,10.0,12.13,0,0,...,0,0,0,0,0,0,0,0,0,0
4,104.37,0.54,71.00,0.44,96.40,7,10.0,12.13,0,0,...,0,0,0,0,0,0,0,0,0,0
5,104.37,0.54,71.00,0.44,96.40,7,10.0,12.13,0,0,...,0,0,0,0,0,0,0,0,0,0
6,103.83,0.61,70.28,0.43,96.54,5,10.0,12.48,0,0,...,0,0,0,0,0,0,0,0,0,0
7,103.83,0.61,70.28,0.43,96.54,5,10.0,12.48,0,0,...,0,0,0,0,0,0,0,0,0,0
8,103.83,0.61,70.28,0.43,96.54,5,10.0,12.48,0,0,...,0,0,0,0,0,0,0,0,0,0
9,103.83,0.61,70.28,0.43,96.54,5,10.0,12.48,0,0,...,0,0,0,0,0,0,0,0,0,0
10,102.97,0.66,69.97,0.43,96.10,3,10.0,12.71,0,0,...,0,0,0,0,0,0,0,0,0,0
11,102.97,0.66,69.97,0.43,96.10,3,10.0,12.71,0,0,...,0,0,0,0,0,0,0,0,0,0
12,102.97,0.66,69.97,0.43,96.10,3,10.0,12.71,0,0,...,0,0,0,0,0,0,0,0,0,0
13,102.97,0.66,69.97,0.43,96.10,3,10.0,12.71,0,0,...,0,0,0,0,0,0,0,0,0,0
14,102.08,0.67,70.25,0.45,95.17,1,10.0,12.77,0,0,...,0,0,0,0,0,0,0,0,0,0
15,102.08,0.67,70.25,0.45,95.17,1,10.0,12.77,0,0,...,0,0,0,0,0,0,0,0,0,0
16,102.08,0.67,70.25,0.45,95.17,1,10.0,12.77,0,0,...,0,0,0,0,0,0,0,0,0,0
17,102.08,0.67,70.25,0.45,95.17,1,10.0,12.77,0,0,...,0,0,0,0,0,0,0,0,0,0
18,100.92,0.65,70.95,0.48,93.69,0,10.0,12.70,0,0,...,0,0,0,0,0,0,0,0,0,0
19,100.92,0.65,70.95,0.48,93.69,0,10.0,12.70,0,0,...,0,0,0,0,0,0,0,0,0,0
20,100.92,0.65,70.95,0.48,93.69,0,10.0,12.70,0,0,...,0,0,0,0,0,0,0,0,0,0
21,100.92,0.65,70.95,0.48,93.69,0,10.0,12.70,0,0,...,0,0,0,0,0,0,0,0,0,0
22,99.31,0.63,71.71,0.52,91.79,0,10.0,12.68,0,0,...,0,0,0,0,0,0,0,0,0,0
23,99.31,0.63,71.71,0.52,91.79,0,10.0,12.68,0,0,...,0,0,0,0,0,0,0,0,0,0
24,99.31,0.63,71.71,0.52,91.79,0,10.0,12.68,0,0,...,0,0,0,0,0,0,0,0,0,0
25,99.31,0.63,71.71,0.52,91.79,0,10.0,12.68,0,0,...,0,0,0,0,0,0,0,0,0,0
26,98.02,0.62,72.41,0.56,90.20,0,10.0,12.94,0,0,...,0,0,0,0,0,0,0,0,0,0
27,98.02,0.62,72.41,0.56,90.20,0,10.0,12.94,0,0,...,0,0,0,0,0,0,0,0,0,0
28,98.02,0.62,72.41,0.56,90.20,0,10.0,12.94,0,0,...,0,0,0,0,0,0,0,0,0,0
29,98.02,0.62,72.41,0.56,90.20,0,10.0,12.94,0,0,...,0,0,0,0,0,0,0,0,0,0
30,96.78,0.60,73.20,0.61,88.61,0,10.0,13.28,0,0,...,0,0,0,0,0,0,0,0,0,0
31,96.78,0.60,73.20,0.61,88.61,0,10.0,13.28,0,0,...,0,0,0,0,0,0,0,0,0,0
32,96.78,0.60,73.20,0.61,88.61,0,10.0,13.28,0,0,...,0,0,0,0,0,0,0,0,0,0
33,96.78,0.60,73.20,0.61,88.61,0,10.0,13.28,0,0,...,0,0,0,0,0,0,0,0,0,0
34,96.02,0.58,73.89,0.64,87.52,0,10.0,13.26,0,0,...,0,0,0,0,0,0,0,0,0,0
35,96.02,0.58,73.89,0.64,87.52,0,10.0,13.26,0,0,...,0,0,0,0,0,0,0,0,0,0
36,96.02,0.58,73.89,0.64,87.52,0,10.0,13.26,0,0,...,0,0,0,0,0,0,0,0,0,0
37,96.02,0.58,73.89,0.64,87.52,0,10.0,13.26,0,0,...,1,0,0,0,0,0,0,0,0,0
38,95.64,0.55,74.48,0.67,86.80,0,10.0,12.59,0,0,...,0,1,0,0,0,0,0,0,0,0
39,95.64,0.55,74.48,0.67,86.80,0,10.0,12.59,0,0,...,0,0,1,0,0,0,0,0,0,0
40,95.64,0.55,74.48,0.67,86.80,0,10.0,12.59,0,0,...,0,0,0,1,0,0,0,0,0,0
41,95.64,0.55,74.48,0.67,86.80,0,10.0,12.59,0,0,...,0,0,0,0,1,0,0,0,0,0
42,95.48,0.51,74.98,0.69,86.32,0,10.0,11.53,0,0,...,0,0,0,0,0,1,0,0,0,0
43,95.48,0.51,74.98,0.69,86.32,0,10.0,11.53,0,0,...,0,0,0,0,0,0,1,0,0,0
44,95.48,0.51,74.98,0.69,86.32,0,10.0,11.53,0,0,...,0,0,0,0,0,0,0,1,0,0
45,95.48,0.51,74.98,0.69,86.32,0,10.0,11.53,0,0,...,0,0,0,0,0,0,0,0,1,0
46,95.06,0.47,75.34,0.71,85.79,0,10.0,10.44,0,0,...,0,0,0,0,0,0,0,0,0,1

In [103]:
path = "tongsdata/"
filedate = filename.split(".")[0].split("-")

with open(path + filename, 'r', encoding='utf-8') as fin:
    data_json = json.loads(fin.read())

#  Create X DataFrame
todayData = {time: data_json[time]['currently'] for time in data_json}
todayData_DF = pd.DataFrame(todayData).T
dropcolumns=['icon', 'summary', 'time', 'windBearing', 'windGust', 'ozone', 'precipIntensity', 'precipProbability','pressure','precipType']
for i in dropcolumns:
    if i in todayData_DF.columns:
        todayData_DF = todayData_DF.drop(columns=[i])
todayData_DF.loc['06:30':'18:00'].to_csv("Realweather.csv")